In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib


In [75]:
class Perceptron:
  def __init__(self,eta,epochs):
    self.weights=np.random.randn(3) * 1e-4
    print(f"self.weights:{self.weights}")
    self.eta=eta
    self.epochs=epochs

  def activationFunction(self,inputs,weights):
    z= np.dot(inputs,weights)
    return np.where(z>0,1,0)

  def fit(self,x,y):
    self.x=x
    self.y=y

    x_with_bias=np.c_[self.x,-np.ones((len(self.x),1))]
    print(f"x_with_bias:\n{x_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch:{epoch}")
      y_hat=self.activationFunction(x_with_bias,self.weights)
      print(f"predicted value:\n{y_hat}")
      error=self.y-y_hat
      print(f"error:\n{error}")
      self.weights=self.weights+self.eta*np.dot(x_with_bias.T,error)
      print(f"updated weights:\n{self.weights}")

  def predict(self,x):
    x_with_bias=np.c_[x,-np.ones((len(self.x),1))]
    return self.activationFunction(x_with_bias,self.weights)

In [76]:
data={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,0,0,1]}
AND=pd.DataFrame(data)
AND

,x1,x2,y
0,0,0,0
1,0,1,0
2,1,0,0
3,1,1,1


In [77]:
x=AND.drop('y',axis=1)
x

,x1,x2
0,0,0
1,0,1
2,1,0
3,1,1


In [78]:
y=AND['y']
y.to_frame()

,y
0,0
1,0
2,0
3,1


In [79]:
model=Perceptron(eta=0.5,epochs=10)
model.fit(x,y)

self.weights:[-7.34496164e-05 -2.93991177e-05 -5.37027859e-09]
x_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch:0
predicted value:
[1 0 0 0]
error:
0   -1
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[ 4.99926550e-01  4.99970601e-01 -5.37027859e-09]
for epoch:1
predicted value:
[1 1 1 1]
error:
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[-7.34496164e-05 -2.93991177e-05  1.49999999e+00]
for epoch:2
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.49992655 0.4999706  0.99999999]
for epoch:3
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.99992655 0.9999706  0.49999999]
for epoch:4
predicted value:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[0.49992655 0.4999706  1.49999999]
for epoch:5
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int

In [80]:
model.fit(x,y)

x_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch:0
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99992655 0.9999706  0.99999999]
for epoch:1
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99992655 0.9999706  0.99999999]
for epoch:2
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99992655 0.9999706  0.99999999]
for epoch:3
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99992655 0.9999706  0.99999999]
for epoch:4
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99992655 0.9999706  0.99999999]
for epoch:5
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.99992655 0.9999706  0.99999999]
for epoch:6
predicted value:
[0 0 0 1]

In [81]:
model.predict(x)

array([0, 0, 0, 1])

In [82]:
model.weights

array([0.99992655, 0.9999706 , 0.99999999])

# OR GATE

In [83]:
d={"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,1,1,1]}

In [84]:
OR=pd.DataFrame(d)
OR

,x1,x2,y
0,0,0,0
1,0,1,1
2,1,0,1
3,1,1,1


In [85]:
x=OR.drop("y",axis=1)
x

,x1,x2
0,0,0
1,0,1
2,1,0
3,1,1


In [86]:
y=OR["y"]
y.to_frame()

,y
0,0
1,1
2,1
3,1


In [87]:
model=Perceptron(eta=0.5,epochs=10)

self.weights:[ 5.65927888e-05 -7.29050931e-05  6.84999751e-05]


In [88]:
model.fit(x,y)

x_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch:0
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights:
[ 1.00005659  0.99992709 -1.4999315 ]
for epoch:1
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[ 1.00005659  0.99992709 -0.9999315 ]
for epoch:2
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[ 1.00005659  0.99992709 -0.4999315 ]
for epoch:3
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[1.00005659e+00 9.99927095e-01 6.84999751e-05]
for epoch:4
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[1.00005659e+00 9.99927095e-01 6.84999751e-05]
for epoch:5
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[1.00005659e+00 9.99927095e-01 6.8499975

In [89]:
model.predict(x)

array([0, 1, 1, 1])

In [90]:
model.weights

array([1.00005659e+00, 9.99927095e-01, 6.84999751e-05])